- name: Remove docker's services and datas
  ansible.builtin.shell: 
    cmd: "make -C {{inception_folder}} fclean"

- name: Remove inception folder
  ansible.builtin.file: 
    path: "{{inception_folder}}"
    state: absent
