---
- name: cloud-1
  hosts: vm
  tasks:

  - name: Download docker's official gpg key (debian)
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/debian/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: 444

  - name: Add docker repository to apt sources
    ansible.builtin.shell:
      cmd: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'

  - name: Install docker packages
    ansible.builtin.apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present
      update_cache: yes

  - name: Copy the inception folder to the home node 
    ansible.builtin.copy:
      src: ./inception
      dest: ~/

  - name: Up wordpress's site after reboot via cron
    ansible.builtin.cron:
      name: "up wordpress site"
      special_time: "reboot"
      job: "make -C ~/inception"

  - name: Launch inception services 
    ansible.builtin.shell:
      cmd: "make -C ~/inception"

