---
- name: test
  hosts: vm
  tasks:
  # wget get.docker.com -> 
  # mv index.html script.sh -> 
  # execute script in sudo 
  # add user to docker group
    - name: Download docker installation script 
      ansible.builtin.get_url:
        url: "https://get.docker.com"
        dest: ~/get_docker.sh
        mode: 777

    - name: Execute docker script installation
      ansible.builtin.shell:
        cmd: "~/get_docker.sh"

    - name: Copy the inception folder to the home node 
      ansible.builtin.copy:
        src: ./inception
        dest: ~/

    - name: Make inside the inception folder 
      ansible.builtin.shell:
        cmd: "make -C ~/inception"
